# Generated by Django 2.0.6 on 2018-06-23 09:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='note',
            managers=[
                ('notes', django.db.models.manager.Manager()),
            ],
        ),
    ]
